CREATE TABLE IF NOT EXISTS transacciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operacion VARCHAR(80) NOT NULL,
    importe DECIMAL(15, 2) NOT NULL CHECK (importe > 0),
    cliente VARCHAR(120) NOT NULL,
    referencia VARCHAR(6) UNIQUE,
    estatus VARCHAR(20) NOT NULL CHECK (estatus IN ('Aprobada', 'Cancelada')),
    secreto VARCHAR(255) NOT NULL
);
